name: docker build and push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: lilong7676/mini_faas_worker:latest

      # 通过 ssh 连接到 server，并执行 docker 运行命令
      -
        name: SSH to server
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.SSH_SECRET}}" > deploy.key
          mkdir -p ~/.ssh
          chmod 0600 deploy.key
          ssh-add deploy.key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh root@${{secrets.SERVER_IP}} '
            #!/bin/bash
            echo "stopping mini_faas_worker..."
            docker stop mini_faas_worker
            echo "mini_faas_worker stopped"

            echo "clean docker ..."
            docker system prune -a -f
            echo "clean docker done"

            echo "pull lilong7676/mini_faas_worker:latest"
            docker pull lilong7676/mini_faas_worker:latest
            echo "pull latest done"

            echo "run mini_faas_worker"
            docker run --name="mini_faas_worker" -d -p 9100:9100 -p 9101:9101 -p 9102:9102 lilong7676/mini_faas_worker:latest
            echo "run mini_faas_worker done"
          '

      - name: delete ssh key
        run: rm -rf ~/.ssh/id_rsa
